In [1]:
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer

pygame 2.1.2 (SDL 2.0.18, Python 3.10.3)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r'C:\Users\adith\OneDrive\Desktop\Ai & ML\dsp driverdrowsiness\dsp driverdrowsiness\models\model.h5')

In [5]:
mixer.init()
sound= mixer.Sound(r"C:\Users\adith\OneDrive\Desktop\Ai & ML\dsp driverdrowsiness\dsp driverdrowsiness\alarm.wav")
cap = cv2.VideoCapture(0)
Score = 0
while True:
    ret, frame = cap.read()
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        #cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        # if eyes are closed
        if prediction[0][0]>0.40:
            cv2.putText(frame,'closed',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>10):
                try:
                    sound.play()
                except:
                    pass
            
        # if eyes are open
        elif prediction[0][1]>0.80:
            cv2.putText(frame,'open',(220,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-1
            if (Score<0):
                Score=0
            
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()
 

1/1 [==============================] - 0s 39ms/step
[[0.27634093 0.72365904]]
1/1 [==============================] - 0s 44ms/step
[[0.9767948  0.02320522]]
1/1 [==============================] - 0s 40ms/step
[[0.28389215 0.7161079 ]]
1/1 [==============================] - 0s 39ms/step
[[0.385895 0.614105]]
1/1 [==============================] - 0s 39ms/step
[[0.1671494  0.83285064]]
1/1 [==============================] - 0s 40ms/step
[[0.34838054 0.65161943]]
1/1 [==============================] - 0s 37ms/step
[[0.99857104 0.00142893]]
1/1 [==============================] - 0s 36ms/step
[[0.7034172 0.2965828]]
1/1 [==============================] - 0s 40ms/step
[[0.70516753 0.2948325 ]]
1/1 [==============================] - 0s 40ms/step
[[0.433129 0.566871]]
1/1 [==============================] - 0s 38ms/step
[[0.5210977  0.47890234]]
1/1 [==============================] - 0s 38ms/step
[[0.02173785 0.9782622 ]]
1/1 [==============================] - 0s 41ms/step
[[0.6913426 0.3086574]